#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "myheader.h"
double func(double x);
int main(){
    Point2D* centre = (Point2D*)malloc(sizeof(Point2D));
    centre->x = 0;
    centre->y = 0;
    Point2D* width_height = (Point2D*)malloc(sizeof(Point2D));
    width_height->x = 100;
    width_height->y = 50;
    Point2D* start = (Point2D*)malloc(sizeof(Point2D)), *end = (Point2D*)malloc(sizeof(Point2D));
    start->x = 0;
    start->y = 0;
    start->next = NULL;
    end->x = 400;
    end->y = 400;
    end->next = NULL;
    Point2D* polyline_points = (Point2D*)malloc(sizeof(Point2D)), *polygon_points = (Point2D*)malloc(sizeof(Point2D));
    polyline_points->x = 50;
    polyline_points->y = 50;
    polyline_points->next = (Point2D*)malloc(sizeof(Point2D));
    polyline_points->next->x = 100;
    polyline_points->next->y = 50;
    polyline_points->next->next = (Point2D*)malloc(sizeof(Point2D));
    polyline_points->next->next->x = 100;
    polyline_points->next->next->y = 50;
    polyline_points->next->next->next = (Point2D*)malloc(sizeof(Point2D));
    polyline_points->next->next->next->x = 70;
    polyline_points->next->next->next->y = 80;
    polyline_points->next->next->next->next = NULL;
    polygon_points->x = 0;
    polygon_points->y = 0;
    polygon_points->next = (Point2D*)malloc(sizeof(Point2D));
    polygon_points->next->x = 30;
    polygon_points->next->y = 0;
    polygon_points->next->next = (Point2D*)malloc(sizeof(Point2D));
    polygon_points->next->next->x = 30;
    polygon_points->next->next->y = 30;
    polygon_points->next->next->next = (Point2D*)malloc(sizeof(Point2D));
    polygon_points->next->next->next->x = 0;
    polygon_points->next->next->next->y = 30;
    polygon_points->next->next->next->next = NULL;
    Tree *root = (Tree*)malloc(sizeof(Tree));
    root->left = (Tree*)malloc(sizeof(Tree));
    root->right = (Tree*)malloc(sizeof(Tree));
    root->x = 10;
    root->left->x = 100;
    root->left->left = (Tree*)malloc(sizeof(Tree));
    root->left->left->x = 4;
    root->left->left->left = NULL;
    root->left->left->right = NULL;
    root->left->right = (Tree*)malloc(sizeof(Tree));
    root->left->right->x = 11;
    root->left->right->left = NULL;
    root->left->right->right = NULL;
    root->right->x = 89;
    root->right->left = NULL;
    root->right->right = (Tree*)malloc(sizeof(Tree));
    root->right->right->x = 54;
    root->right->right->left = NULL;
    root->right->right->right = NULL;
    Figure *function, *polyline, *polygon, *ellipse, *binary_tree;
    Color color_ratios;
    color_ratios.red = 0;
    color_ratios.green = 0.5;
    color_ratios.blue = 0;
    function = start_figure(500, 500);
    polyline = start_figure(500, 500);
    polygon = start_figure(500, 500);
    ellipse = start_figure(500, 500);
    binary_tree = start_figure(500, 500);
    set_thickness_resolution(function, 2, 0.00001);
    set_thickness_resolution(polyline, 3, 0.00001);
    set_thickness_resolution(polygon, 1, 0.00001);
    set_thickness_resolution(ellipse, 2, 0.00001);
    set_thickness_resolution(binary_tree, 1, 0.00001);
    set_color(function, color_ratios);
    set_color(polyline, color_ratios);
    set_color(polygon, color_ratios);
    set_color(ellipse, color_ratios);
    set_color(binary_tree, color_ratios);
    draw_fx(function, func, -10.0, 10.0, 1);
    draw_polyline(polyline_points, 4, polyline);
    draw_polygon(polygon_points, polygon);
    draw_ellipse(centre, width_height, ellipse);
    draw_binary_tree(root, binary_tree->binarytree);
    export_eps(function, "fx.eps");
    export_eps(polyline, "polyline.eps");
    export_eps(polygon, "polygon.eps");
    export_eps(ellipse, "ellipse.eps");
    export_eps(binary_tree, "binary_tree.eps");
    scale_figure(2.0, 2.0, polygon);
    export_eps(polygon, "scale.eps");
    resize_figure(start, end, binary_tree);
    export_eps(binary_tree, "resize.eps");
    append_figures(ellipse, binary_tree);
    export_eps(ellipse, "append.eps");
    free(centre);
    free(width_height);
    free(start);
    free(end);
    free(polyline_points);
    free(polygon_points);
    free(root);
    free(function);
    free(polyline);
    free(polygon);
    free(ellipse);
    free(binary_tree);
    return 0;
}
double func(double x){
    return pow(x, 2);
}